package cz.ioff.app;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.text.*;
import java.util.*;

public class MainActivity extends Activity {
    final int BG=Color.rgb(246,246,242), INK=Color.rgb(20,20,20), MUTED=Color.rgb(100,100,96);
    LinearLayout root, content, nav; android.content.SharedPreferences prefs; CountDownTimer timer; long left=0; int urges=0;
    String[] days={"BASELINE","REMOVE TRIGGERS","TRAIN BOREDOM","OWN YOUR MORNING","BREAK THE FEED","GO DEEP","SILENCE & MEASURE"};
    String[] missions={"60 min on one important thing. Measure, don't judge.","Remove triggers. Complete two 60 min focus blocks.","30 min without input. No phone, music or podcast. Then focus.","90 min deep work before feeds, news or email.","24 hours without algorithmic feeds. Direct communication is OK.","One problem. 120 minutes. Every side idea goes to Parking Lot.","Three low-input hours, then review what changed."};

    public void onCreate(Bundle b){super.onCreate(b); prefs=getSharedPreferences("ioff",0); showToday();}
    TextView t(String s,int sp,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(INK);v.setPadding(0,8,0,8); if(bold)v.setTypeface(null,1);return v;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setTextColor(Color.WHITE);b.setBackgroundColor(INK);b.setAllCaps(false);b.setPadding(12,12,12,12);return b;}
    void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(28,26,28,10); content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL); ScrollView sv=new ScrollView(this);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);String[] ns={"Today","Focus","Ideas","Progress","Control"};for(String n:ns){Button x=new Button(this);x.setText(n);x.setAllCaps(false);x.setTextSize(11);x.setBackgroundColor(Color.TRANSPARENT);x.setOnClickListener(v->{if(n.equals("Today"))showToday();if(n.equals("Focus"))showFocus();if(n.equals("Ideas"))showIdeas();if(n.equals("Progress"))showProgress();if(n.equals("Control"))showControl();});nav.addView(x,new LinearLayout.LayoutParams(0,60,1));}root.addView(nav);setContentView(root);content.addView(t("iOff",30,true));content.addView(t(title,13,true));}
    int day(){return Math.min(7,Math.max(1,prefs.getInt("day",1)));}
    void showToday(){base("TODAY");int d=day();content.addView(t("DAY "+d+" / 7",14,true));content.addView(t("TAKE BACK YOUR ATTENTION",25,true));content.addView(t("● ".repeat(d)+"○ ".repeat(7-d),20,false));content.addView(t("TODAY'S MISSION",12,true));content.addView(t(days[d-1],23,true));content.addView(t(missions[d-1],17,false));Button f=btn("START FOCUS");f.setOnClickListener(v->showFocus());content.addView(f);content.addView(t("\nTODAY",12,true));content.addView(t("Deep work  "+prefs.getInt("mins",0)+" min\nUrges  "+prefs.getInt("urges",0)+"\nIdeas parked  "+countIdeas(),18,false));Button i=btn("+ PARK AN IDEA");i.setOnClickListener(v->ideaDialog());content.addView(i);Button done=btn("COMPLETE DAY →");done.setOnClickListener(v->{if(day()<7)prefs.edit().putInt("day",day()+1).apply();showToday();});content.addView(done);}
    void showFocus(){base("FOCUS");content.addView(t("WHAT WILL EXIST WHEN YOU FINISH?",18,true));EditText goal=new EditText(this);goal.setHint("One concrete output");goal.setText(prefs.getString("goal",""));content.addView(goal);content.addView(t("DURATION",12,true));LinearLayout row=new LinearLayout(this);for(int m:new int[]{30,60,90,120}){Button b=new Button(this);b.setText(m+"m");b.setOnClickListener(v->{prefs.edit().putInt("duration",m).apply();});row.addView(b,new LinearLayout.LayoutParams(0,55,1));}content.addView(row);Button start=btn("BEGIN FOCUS");start.setOnClickListener(v->{prefs.edit().putString("goal",goal.getText().toString()).apply();startTimer(prefs.getInt("duration",60));});content.addView(start);content.addView(t("\nDuring focus: one thing only. New thought? Park it. Impulse to switch? Count it.",16,false));}
    void startTimer(int mins){base("FOCUS SESSION");urges=0;left=mins*60000L;TextView clock=t("",48,true);clock.setGravity(Gravity.CENTER);content.addView(clock);TextView g=t(prefs.getString("goal","Stay with one thing."),20,true);g.setGravity(Gravity.CENTER);content.addView(g);TextView u=t("Urges: 0",16,false);u.setGravity(Gravity.CENTER);content.addView(u);Button urge=btn("I FEEL AN URGE");urge.setOnClickListener(v->{urges++;u.setText("Urges: "+urges);});content.addView(urge);Button idea=btn("+ PARK IDEA");idea.setOnClickListener(v->ideaDialog());content.addView(idea);Button end=new Button(this);end.setText("END EARLY");end.setOnClickListener(v->{timer.cancel();finishFocus(mins);});content.addView(end);timer=new CountDownTimer(left,1000){public void onTick(long ms){left=ms;clock.setText(String.format(Locale.US,"%02d:%02d:%02d",ms/3600000,(ms/60000)%60,(ms/1000)%60));}public void onFinish(){finishFocus(mins);}}.start();}
    void finishFocus(int planned){base("SESSION COMPLETE");int actual=(int)Math.max(1,(planned*60000L-left)/60000L);prefs.edit().putInt("mins",prefs.getInt("mins",0)+actual).putInt("urges",prefs.getInt("urges",0)+urges).apply();content.addView(t(actual+" MIN COMPLETE",30,true));content.addView(t("Urges: "+urges+"\nIdeas parked: "+countIdeas(),18,false));EditText out=new EditText(this);out.setHint("What did you produce?");content.addView(out);content.addView(t("Focus rating 1–10",14,true));SeekBar s=new SeekBar(this);s.setMax(9);s.setProgress(6);content.addView(s);Button save=btn("SAVE SESSION");save.setOnClickListener(v->{prefs.edit().putInt("focus",s.getProgress()+1).putString("output",out.getText().toString()).apply();showToday();});content.addView(save);}
    void ideaDialog(){final EditText input=new EditText(this);input.setHint("Get it out of your head…");new AlertDialog.Builder(this).setTitle("Park idea").setView(input).setNegativeButton("Cancel",null).setPositiveButton("PARK",(d,w)->{String x=input.getText().toString().trim();if(!x.isEmpty()){String old=prefs.getString("ideas","");prefs.edit().putString("ideas",System.currentTimeMillis()+"|"+x+"\n"+old).apply();}}).show();}
    int countIdeas(){String s=prefs.getString("ideas","").trim();return s.isEmpty()?0:s.split("\\n").length;}
    void showIdeas(){base("IDEA PARKING LOT");content.addView(t(countIdeas()+" IDEAS WAITING",18,true));Button add=btn("+ PARK IDEA");add.setOnClickListener(v->ideaDialog());content.addView(add);String s=prefs.getString("ideas","");if(s.trim().isEmpty())content.addView(t("\nEmpty. During focus, every side idea belongs here.",16,false));else for(String line:s.split("\\n")){String[] p=line.split("\\|",2);if(p.length==2){Date dt=new Date(Long.parseLong(p[0]));content.addView(t("●  "+p[1]+"\n    "+new SimpleDateFormat("dd/MM HH:mm",Locale.getDefault()).format(dt),17,false));}}Button clear=new Button(this);clear.setText("Clear reviewed ideas");clear.setOnClickListener(v->{prefs.edit().remove("ideas").apply();showIdeas();});content.addView(clear);}
    void showProgress(){base("PROGRESS");int mins=prefs.getInt("mins",0),u=prefs.getInt("urges",0),f=prefs.getInt("focus",0);content.addView(t("ATTENTION, NOT STREAKS.",24,true));content.addView(t("Deep work\n"+mins+" min\n\nUrges\n"+u+"\n\nLast focus rating\n"+(f==0?"—":f+" / 10")+"\n\nIdeas parked\n"+countIdeas(),22,false));content.addView(t("\nAfter seven days this screen becomes your Before → After report.",15,false));}
    void showControl(){base("CONTROL");content.addView(t("CONTROL YOUR ENVIRONMENT",23,true));content.addView(t("iOff cannot silently rewrite another app's notification settings. Android does let you grant focus-related access and control Do Not Disturb from system settings.",15,false));Button dnd=btn("DO NOT DISTURB ACCESS");dnd.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_NOTIFICATION_POLICY_ACCESS_SETTINGS)));content.addView(dnd);Button usage=btn("USAGE ACCESS");usage.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS)));content.addView(usage);Button notif=btn("APP NOTIFICATION SETTINGS");notif.setOnClickListener(v->{Intent i=new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS);i.putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName());startActivity(i);});content.addView(notif);content.addView(t("\nMVP is local-first. No account. No cloud. No feed.",15,false));}
}
