package cz.ioff.app;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.text.*;
import java.util.*;

public class MainActivity extends Activity {
    final int BG=Color.rgb(10,12,16), CARD=Color.rgb(20,23,30), CARD2=Color.rgb(27,31,40), INK=Color.rgb(244,246,250), MUTED=Color.rgb(151,159,174), ACCENT=Color.rgb(130,255,177), BLUE=Color.rgb(116,180,255), DANGER=Color.rgb(255,112,112);
    LinearLayout root, content, nav; SharedPreferences prefs; CountDownTimer timer; long left=0; int urges=0;
    String[] days={"BASELINE","REMOVE TRIGGERS","TRAIN BOREDOM","OWN YOUR MORNING","BREAK THE FEED","GO DEEP","SILENCE & MEASURE"};
    String[] missions={"60 min on one important thing. Measure, don't judge.","Remove triggers. Complete two 60 min focus blocks.","30 min without input. No phone, music or podcast. Then focus.","90 min deep work before feeds, news or email.","24 hours without algorithmic feeds. Direct communication is OK.","One problem. 120 minutes. Every side idea goes to Parking Lot.","Three low-input hours, then review what changed."};

    public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("ioff",0);showToday();}
    int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    GradientDrawable bg(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
    TextView t(String s,int sp,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(INK);v.setPadding(0,dp(6),0,dp(6));if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
    TextView muted(String s,int sp){TextView v=t(s,sp,false);v.setTextColor(MUTED);return v;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setTextColor(BG);b.setTypeface(null,Typeface.BOLD);b.setBackground(bg(ACCENT,16));b.setAllCaps(false);b.setPadding(dp(16),dp(12),dp(16),dp(12));return b;}
    Button ghost(String s){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setTextColor(INK);b.setBackground(bg(CARD2,14));b.setAllCaps(false);return b;}
    LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(16),dp(18),dp(16));c.setBackground(bg(CARD,20));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(8),0,dp(8));c.setLayoutParams(lp);return c;}
    void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(20),dp(18),dp(20),dp(24));ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setPadding(dp(4),dp(3),dp(4),dp(6));nav.setBackgroundColor(Color.rgb(14,16,21));String[] ns={"Today","Focus","Ideas","Progress","Control"};for(String n:ns){Button x=new Button(this);x.setText(n);x.setAllCaps(false);x.setTextSize(11);x.setTextColor(MUTED);x.setBackgroundColor(Color.TRANSPARENT);x.setOnClickListener(v->{if(n.equals("Today"))showToday();else if(n.equals("Focus"))showFocus();else if(n.equals("Ideas"))showIdeas();else if(n.equals("Progress"))showProgress();else showControl();});nav.addView(x,new LinearLayout.LayoutParams(0,dp(56),1));}root.addView(nav);setContentView(root);LinearLayout brand=new LinearLayout(this);brand.setGravity(Gravity.CENTER_VERTICAL);TextView logo=t("iOff",30,true);logo.setTextColor(ACCENT);brand.addView(logo,new LinearLayout.LayoutParams(0,-2,1));TextView section=muted(title,12);section.setGravity(Gravity.RIGHT);brand.addView(section);content.addView(brand);}
    int day(){return Math.min(7,Math.max(1,prefs.getInt("day",1)));}
    void setDay(int d){prefs.edit().putInt("day",Math.max(1,Math.min(7,d))).apply();showToday();}
    String dots(int d){StringBuilder s=new StringBuilder();for(int i=1;i<=7;i++)s.append(i==d?"● ":i<d?"● ":"○ ");return s.toString();}
    void showToday(){base("TODAY");int d=day();TextView hero=t("TAKE BACK\nYOUR ATTENTION",34,true);hero.setLetterSpacing(.02f);content.addView(hero);content.addView(muted("Day "+d+" of 7  •  your attention reset",14));TextView prog=t(dots(d),20,true);prog.setTextColor(ACCENT);content.addView(prog);
        LinearLayout mission=card();mission.addView(muted("TODAY'S MISSION",11));TextView mt=t(days[d-1],23,true);mt.setTextColor(ACCENT);mission.addView(mt);mission.addView(muted(missions[d-1],16));content.addView(mission);
        Button f=btn("START FOCUS  →");f.setOnClickListener(v->showFocus());content.addView(f);
        LinearLayout stats=card();stats.addView(muted("TODAY",11));stats.addView(t(prefs.getInt("mins",0)+" min  ·  "+prefs.getInt("urges",0)+" urges  ·  "+countIdeas()+" ideas",18,true));content.addView(stats);
        Button idea=ghost("＋  PARK AN IDEA");idea.setOnClickListener(v->ideaDialog());content.addView(idea);
        LinearLayout dayrow=new LinearLayout(this);dayrow.setPadding(0,dp(10),0,0);Button prev=ghost("← Previous day");prev.setEnabled(d>1);prev.setAlpha(d>1?1f:.35f);prev.setOnClickListener(v->setDay(day()-1));Button next=ghost(d==7?"Day 7":"Complete day →");next.setOnClickListener(v->{if(day()<7)setDay(day()+1);});dayrow.addView(prev,new LinearLayout.LayoutParams(0,dp(52),1));Space sp=new Space(this);dayrow.addView(sp,new LinearLayout.LayoutParams(dp(8),1));dayrow.addView(next,new LinearLayout.LayoutParams(0,dp(52),1));content.addView(dayrow);
    }
    void showFocus(){base("FOCUS");content.addView(t("ONE THING.\nUNTIL IT'S DONE.",30,true));content.addView(muted("Define the result before starting. Everything else waits.",15));LinearLayout c=card();c.addView(muted("WHAT WILL EXIST WHEN YOU FINISH?",11));EditText goal=new EditText(this);goal.setHint("One concrete output");goal.setHintTextColor(MUTED);goal.setTextColor(INK);goal.setSingleLine(false);goal.setText(prefs.getString("goal",""));c.addView(goal);content.addView(c);content.addView(muted("DURATION",11));LinearLayout row=new LinearLayout(this);for(int m:new int[]{30,60,90,120}){Button b=ghost(m+" min");b.setOnClickListener(v->{prefs.edit().putInt("duration",m).apply();Toast.makeText(this,m+" minutes selected",Toast.LENGTH_SHORT).show();});row.addView(b,new LinearLayout.LayoutParams(0,dp(54),1));}content.addView(row);Button start=btn("BEGIN FOCUS  →");start.setOnClickListener(v->{prefs.edit().putString("goal",goal.getText().toString()).apply();startTimer(prefs.getInt("duration",60));});content.addView(start);content.addView(muted("\nImpulse to switch? Tap Urge. New thought? Park it. Neither requires leaving the session.",14));}
    void startTimer(int mins){base("FOCUS SESSION");urges=0;left=mins*60000L;TextView label=muted("STAY WITH ONE THING",12);label.setGravity(Gravity.CENTER);content.addView(label);TextView clock=t("",52,true);clock.setTextColor(ACCENT);clock.setGravity(Gravity.CENTER);clock.setPadding(0,dp(30),0,dp(20));content.addView(clock);TextView g=t(prefs.getString("goal","Stay with one thing."),20,true);g.setGravity(Gravity.CENTER);content.addView(g);TextView u=muted("0 urges",15);u.setGravity(Gravity.CENTER);content.addView(u);Button urge=ghost("I FEEL AN URGE");urge.setOnClickListener(v->{urges++;u.setText(urges+" urges");});content.addView(urge);Button idea=ghost("＋ PARK IDEA");idea.setOnClickListener(v->ideaDialog());content.addView(idea);Button end=ghost("End session early");end.setTextColor(DANGER);end.setOnClickListener(v->{timer.cancel();finishFocus(mins);});content.addView(end);timer=new CountDownTimer(left,1000){public void onTick(long ms){left=ms;clock.setText(String.format(Locale.US,"%02d:%02d:%02d",ms/3600000,(ms/60000)%60,(ms/1000)%60));}public void onFinish(){left=0;finishFocus(mins);}}.start();}
    void finishFocus(int planned){base("SESSION COMPLETE");int actual=(int)Math.max(1,(planned*60000L-left)/60000L);prefs.edit().putInt("mins",prefs.getInt("mins",0)+actual).putInt("urges",prefs.getInt("urges",0)+urges).apply();TextView big=t(actual+" MINUTES",34,true);big.setTextColor(ACCENT);content.addView(big);content.addView(muted("You stayed with it. Now capture the result.",15));LinearLayout c=card();c.addView(t("Urges  "+urges+"   ·   Ideas  "+countIdeas(),17,true));EditText out=new EditText(this);out.setHint("What did you produce?");out.setHintTextColor(MUTED);out.setTextColor(INK);c.addView(out);c.addView(muted("FOCUS RATING 1–10",11));SeekBar s=new SeekBar(this);s.setMax(9);s.setProgress(6);c.addView(s);content.addView(c);Button save=btn("SAVE SESSION");save.setOnClickListener(v->{prefs.edit().putInt("focus",s.getProgress()+1).putString("output",out.getText().toString()).apply();showToday();});content.addView(save);}
    void ideaDialog(){final EditText input=new EditText(this);input.setHint("Get it out of your head…");new AlertDialog.Builder(this).setTitle("Park idea").setView(input).setNegativeButton("Cancel",null).setPositiveButton("PARK",(d,w)->{String x=input.getText().toString().trim();if(!x.isEmpty()){String old=prefs.getString("ideas","");prefs.edit().putString("ideas",System.currentTimeMillis()+"|"+x+"\n"+old).apply();}}).show();}
    int countIdeas(){String s=prefs.getString("ideas","").trim();return s.isEmpty()?0:s.split("\\n").length;}
    void showIdeas(){base("IDEAS");content.addView(t("PARK IT.\nDON'T CHASE IT.",30,true));content.addView(muted(countIdeas()+" ideas waiting. Review them outside focus time.",15));Button add=btn("＋ PARK IDEA");add.setOnClickListener(v->ideaDialog());content.addView(add);String s=prefs.getString("ideas","");if(s.trim().isEmpty())content.addView(muted("\nYour parking lot is empty.",16));else for(String line:s.split("\\n")){String[] p=line.split("\\|",2);if(p.length==2){LinearLayout c=card();Date dt=new Date(Long.parseLong(p[0]));c.addView(t(p[1],17,true));c.addView(muted(new SimpleDateFormat("dd/MM · HH:mm",Locale.getDefault()).format(dt),12));content.addView(c);}}Button clear=ghost("Clear all ideas");clear.setOnClickListener(v->confirmClearIdeas());content.addView(clear);}
    void confirmClearIdeas(){new AlertDialog.Builder(this).setTitle("Clear Parking Lot?").setMessage("This removes all parked ideas.").setNegativeButton("Cancel",null).setPositiveButton("Clear",(d,w)->{prefs.edit().remove("ideas").apply();showIdeas();}).show();}
    void showProgress(){base("PROGRESS");int mins=prefs.getInt("mins",0),u=prefs.getInt("urges",0),f=prefs.getInt("focus",0);content.addView(t("MEASURE CHANGE,\nNOT STREAKS.",29,true));LinearLayout c=card();TextView a=t(mins+"",38,true);a.setTextColor(ACCENT);c.addView(a);c.addView(muted("minutes of deep work",14));content.addView(c);LinearLayout c2=card();c2.addView(t(u+" urges",24,true));c2.addView(muted("noticed instead of automatically followed",14));content.addView(c2);LinearLayout c3=card();c3.addView(t(f==0?"—":f+" / 10",24,true));c3.addView(muted("last focus rating",14));content.addView(c3);content.addView(muted("After day 7 this becomes your Before → After report.",14));}
    void showControl(){base("CONTROL");content.addView(t("DESIGN YOUR\nENVIRONMENT.",30,true));content.addView(muted("Less willpower. More deliberate friction.",15));LinearLayout access=card();access.addView(muted("ANDROID ACCESS",11));Button dnd=ghost("Do Not Disturb access  →");dnd.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_NOTIFICATION_POLICY_ACCESS_SETTINGS)));access.addView(dnd);Button usage=ghost("Usage access  →");usage.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS)));access.addView(usage);Button notif=ghost("iOff notification settings  →");notif.setOnClickListener(v->{Intent i=new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS);i.putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName());startActivity(i);});access.addView(notif);content.addView(access);LinearLayout experiment=card();experiment.addView(muted("EXPERIMENT",11));experiment.addView(t("Current day: "+day()+" / 7",18,true));Button choose=ghost("Choose experiment day");choose.setOnClickListener(v->chooseDay());experiment.addView(choose);Button reset=ghost("Reset experiment & stats");reset.setTextColor(DANGER);reset.setOnClickListener(v->confirmReset());experiment.addView(reset);content.addView(experiment);content.addView(muted("All data stays on this phone. No account. No cloud. No feed.",13));}
    void chooseDay(){String[] x=new String[7];for(int i=0;i<7;i++)x[i]="Day "+(i+1)+" — "+days[i];new AlertDialog.Builder(this).setTitle("Go to day").setSingleChoiceItems(x,day()-1,(d,which)->{prefs.edit().putInt("day",which+1).apply();d.dismiss();showToday();}).setNegativeButton("Cancel",null).show();}
    void confirmReset(){new AlertDialog.Builder(this).setTitle("Reset iOff experiment?").setMessage("Day returns to 1 and focus statistics are cleared. You can choose whether to keep your Parking Lot.").setNegativeButton("Cancel",null).setNeutralButton("Reset + keep ideas",(d,w)->reset(false)).setPositiveButton("Reset everything",(d,w)->reset(true)).show();}
    void reset(boolean ideas){SharedPreferences.Editor e=prefs.edit();String saved=prefs.getString("ideas","");e.clear().apply();if(!ideas&&!saved.isEmpty())prefs.edit().putString("ideas",saved).apply();showToday();}
}
