package cz.ioff.app

import android.app.*
import android.app.usage.UsageStatsManager
import android.content.*
import android.os.*
import android.provider.Settings
import android.speech.RecognizerIntent
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.animation.*
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.*
import kotlinx.coroutines.delay
import org.json.*
import java.text.SimpleDateFormat
import java.util.*

private val Bg=Color(0xFF080A0D); private val Surface=Color(0xFF111419); private val Surface2=Color(0xFF181C22); private val Ink=Color(0xFFF5F7F8); private val Muted=Color(0xFF969DA8); private val Mint=Color(0xFF8AFFB5); private val Warn=Color(0xFFFFCC66); private val Err=Color(0xFFFF7070)
private val Days=listOf("BASELINE","REMOVE TRIGGERS","TRAIN BOREDOM","OWN YOUR MORNING","BREAK THE FEED","GO DEEP","SILENCE & MEASURE")
private val Missions=listOf("60 min on one important thing. Measure, don't judge.","Remove triggers. Complete two 60 min focus blocks.","30 min without input. Then focus.","90 min deep work before feeds, news or email.","24 hours without algorithmic feeds.","One problem. 120 minutes. Park every side idea.","Three low-input hours, then review what changed.")

data class Session(val start:Long,val end:Long,val experimentDay:Int,val planned:Int,val actual:Int,val urges:Int,val focus:Int,val goal:String,val output:String,val interrupted:Boolean)
class Store(private val c:Context){val p=c.getSharedPreferences("ioff",0); fun day()=p.getInt("day",1).coerceIn(1,7); fun k(key:String,d:Int=day())=MetricKeys.experiment(d,key); fun metric(key:String,d:Int=day())=p.getInt(k(key,d),0); fun add(key:String,n:Int,d:Int=day())=p.edit().putInt(k(key,d),metric(key,d)+n).apply(); fun total(key:String)=(1..7).sumOf{metric(key,it)}
 fun sessions():List<Session>{return try{val a=JSONArray(p.getString("sessions_json","[]"));(0 until a.length()).map{val o=a.getJSONObject(it);Session(o.optLong("start"),o.optLong("end"),o.optInt("experimentDay",1),o.optInt("planned"),o.optInt("actual"),o.optInt("urges"),o.optInt("focus"),o.optString("goal"),o.optString("output"),o.optBoolean("interrupted"))}}catch(e:Exception){emptyList()}}
 fun save(s:Session){val a=try{JSONArray(p.getString("sessions_json","[]"))}catch(e:Exception){JSONArray()};a.put(JSONObject().put("start",s.start).put("end",s.end).put("experimentDay",s.experimentDay).put("planned",s.planned).put("actual",s.actual).put("urges",s.urges).put("focus",s.focus).put("goal",s.goal).put("output",s.output).put("interrupted",s.interrupted));p.edit().putString("sessions_json",a.toString()).apply();add("mins",s.actual,s.experimentDay);add("urges",s.urges,s.experimentDay);add("sessions",1,s.experimentDay);add("focusSum",s.focus,s.experimentDay)}
}
class MainActivity:ComponentActivity(){lateinit var store:Store; private val voice=registerForActivityResult(ActivityResultContracts.StartActivityForResult()){r->if(r.resultCode==RESULT_OK){r.data?.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS)?.firstOrNull()?.let{park(it)}}}
 override fun onCreate(b:Bundle?){super.onCreate(b);store=Store(this);recover();setContent{IoffTheme{App(this,store)}}}
 fun startFocus(goal:String,min:Int){val now=System.currentTimeMillis();store.p.edit().putBoolean("focus_active",true).putLong("focus_start",now).putLong("focus_end",now+min*60000L).putInt("focus_day",store.day()).putInt("focus_planned",min).putInt("focus_urges",0).putString("goal",goal).apply();enableDnd()}
 fun finish(interrupted:Boolean):Session{val p=store.p;val start=p.getLong("focus_start",System.currentTimeMillis());val planned=p.getInt("focus_planned",60);var actual=((System.currentTimeMillis()-start)/60000L).toInt().coerceAtLeast(0);if(!interrupted)actual=actual.coerceAtLeast(planned);val s=Session(start,System.currentTimeMillis(),p.getInt("focus_day",store.day()),planned,actual,p.getInt("focus_urges",0),0,p.getString("goal","")?:"","",interrupted);restoreDnd();return s}
 fun complete(s:Session,focus:Int,output:String){store.save(s.copy(focus=focus,output=output));store.p.edit().putBoolean("focus_active",false).apply()}
 fun park(text:String){if(text.isBlank())return;val old=store.p.getString("ideas","")?:"";store.p.edit().putString("ideas","${System.currentTimeMillis()}|${text.trim()}\n$old").apply();store.add("ideas",1,store.p.getInt("focus_day",store.day()))}
 fun voice(){runCatching{voice.launch(Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM))}}
 fun dndGranted()=(getSystemService(NotificationManager::class.java)?.isNotificationPolicyAccessGranted==true); fun enableDnd(){getSystemService(NotificationManager::class.java)?.let{if(it.isNotificationPolicyAccessGranted){store.p.edit().putInt("prev_filter",it.currentInterruptionFilter).apply();it.setInterruptionFilter(NotificationManager.INTERRUPTION_FILTER_PRIORITY)}}}; fun restoreDnd(){getSystemService(NotificationManager::class.java)?.let{if(it.isNotificationPolicyAccessGranted)runCatching{it.setInterruptionFilter(store.p.getInt("prev_filter",NotificationManager.INTERRUPTION_FILTER_ALL))}}}
 fun recover(){if(store.p.getBoolean("focus_active",false)&&store.p.getLong("focus_end",0)<=System.currentTimeMillis()){restoreDnd()}}
 fun usage():Long?=runCatching{val u=getSystemService(UsageStatsManager::class.java);val c=Calendar.getInstance().apply{set(Calendar.HOUR_OF_DAY,0);set(Calendar.MINUTE,0);set(Calendar.SECOND,0)};val b=store.p.getStringSet("blocked_apps",setOf("com.instagram.android","com.facebook.katana","com.zhiliaoapp.musically","com.google.android.youtube","com.twitter.android","com.reddit.frontpage"))!!;u.queryUsageStats(UsageStatsManager.INTERVAL_DAILY,c.timeInMillis,System.currentTimeMillis()).filter{it.packageName in b}.sumOf{it.totalTimeInForeground}}.getOrNull()
}
@Composable fun IoffTheme(content:@Composable()->Unit){MaterialTheme(colorScheme=darkColorScheme(primary=Mint,background=Bg,surface=Surface,onBackground=Ink,onSurface=Ink,error=Err),typography=Typography(),content=content)}
@Composable fun App(a:MainActivity,s:Store){var tab by remember{mutableIntStateOf(0)};var tick by remember{mutableIntStateOf(0)};val active=s.p.getBoolean("focus_active",false);Scaffold(containerColor=Bg,bottomBar={if(!active)NavigationBar(containerColor=Surface){listOf(Icons.Outlined.Home,Icons.Outlined.Timer,Icons.Outlined.Insights,Icons.Outlined.Tune).forEachIndexed{i,ic->NavigationBarItem(selected=tab==i,onClick={tab=i;tick++},icon={Icon(ic,null)},label={Text(listOf("Today","Focus","Progress","More")[i])})}}}){pad->Box(Modifier.padding(pad)){if(active)ActiveFocus(a,s){tick++}else when(tab){0->Today(a,s,tick){tab=1};1->FocusSetup(a,s){tick++};2->Progress(a,s,tick);else->More(a,s){tick++}}}}}
@Composable fun Page(title:String,content:@Composable ColumnScope.()->Unit){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp)){Row(verticalAlignment=Alignment.CenterVertically){Text("iOff",fontSize=28.sp,fontWeight=FontWeight.Bold,color=Mint);Spacer(Modifier.weight(1f));Text(title.uppercase(),fontSize=11.sp,color=Muted)};Spacer(Modifier.height(22.dp));content()}}
@Composable fun CardX(content:@Composable ColumnScope.()->Unit){Card(colors=CardDefaults.cardColors(containerColor=Surface),shape=RoundedCornerShape(24.dp),modifier=Modifier.fillMaxWidth().padding(vertical=7.dp)){Column(Modifier.padding(20.dp),content=content)}}
@Composable fun Primary(text:String,on:()->Unit){Button(onClick=on,modifier=Modifier.fillMaxWidth().height(58.dp),shape=RoundedCornerShape(18.dp),colors=ButtonDefaults.buttonColors(containerColor=Mint,contentColor=Bg)){Text(text,fontWeight=FontWeight.Bold)}}
@Composable fun Today(a:MainActivity,s:Store,tick:Int,toFocus:()->Unit){val d=s.day();Page("Today"){Text("Day $d of 7",color=Muted,fontSize=14.sp);Spacer(Modifier.height(8.dp));Row(Modifier.fillMaxWidth()){(1..7).forEach{Box(Modifier.weight(1f).padding(3.dp).height(if(it==d)7.dp else 4.dp).background(if(it<=d)Mint else Surface2,CircleShape))}};Spacer(Modifier.height(22.dp));CardX{Text(Days[d-1],fontSize=27.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(8.dp));Text(Missions[d-1],color=Muted,fontSize=16.sp);Spacer(Modifier.height(18.dp));Primary("Start focus",toFocus)};Text("TODAY'S PULSE",color=Muted,fontSize=11.sp,modifier=Modifier.padding(top=20.dp,bottom=5.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Metric("DEEP WORK","${s.metric("mins")}m",Modifier.weight(1f));Metric("FOCUS",if(s.metric("sessions")==0)"—" else "%.1f".format(s.metric("focusSum").toDouble()/s.metric("sessions")),Modifier.weight(1f));Metric("URGES","${s.metric("urges")}",Modifier.weight(1f))};val us=a.usage();CardX{Text("ATTENTION BALANCE",color=Muted,fontSize=11.sp);Text("${s.metric("mins")}m deep work",fontSize=22.sp,fontWeight=FontWeight.Bold);Text(if(us==null)"Usage access needed for distraction data" else "${us/60000}m distracting apps today",color=Muted)};val sessions=s.sessions().filter{it.experimentDay==d};Text("TODAY'S FOCUS",color=Muted,fontSize=11.sp,modifier=Modifier.padding(top=18.dp));if(sessions.isEmpty())Empty("No sessions yet","Your first focused block will appear here.")else sessions.takeLast(3).reversed().forEach{SessionRow(it)};OutlinedButton(onClick={IdeaSheet.show=true},modifier=Modifier.fillMaxWidth()){Icon(Icons.Outlined.Lightbulb,null);Spacer(Modifier.width(8.dp));Text("Park idea")};IdeaSheet(a)} }
@Composable fun Metric(label:String,value:String,m:Modifier){Card(colors=CardDefaults.cardColors(containerColor=Surface),shape=RoundedCornerShape(20.dp),modifier=m){Column(Modifier.padding(14.dp)){Text(label,color=Muted,fontSize=10.sp);Text(value,fontSize=23.sp,fontWeight=FontWeight.Bold)}}}
@Composable fun SessionRow(x:Session){CardX{Row{Column(Modifier.weight(1f)){Text(x.goal,fontWeight=FontWeight.SemiBold);Text("${x.actual} min · ${x.urges} urges",color=Muted,fontSize=13.sp)};Text(if(x.focus>0)"${x.focus}/10" else "—",color=Mint)}}}
@Composable fun Empty(title:String,body:String){CardX{Icon(Icons.Outlined.Spa,null,tint=Mint);Text(title,fontSize=18.sp,fontWeight=FontWeight.Bold);Text(body,color=Muted)}}
@Composable fun FocusSetup(a:MainActivity,s:Store,refresh:()->Unit){var goal by remember{mutableStateOf("")};var min by remember{mutableIntStateOf(60)};Page("Focus"){Text("What are you finishing?",fontSize=32.sp,fontWeight=FontWeight.Bold);Text("Define the concrete thing that will exist when you stop.",color=Muted);Spacer(Modifier.height(20.dp));OutlinedTextField(goal,{goal=it},Modifier.fillMaxWidth(),placeholder={Text("Finish the proposal")},minLines=2,shape=RoundedCornerShape(20.dp));Row(Modifier.padding(vertical=16.dp),horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf(30,60,90,120).forEach{x->FilterChip(selected=min==x,onClick={min=x},label={Text("${x}m")})}};CardX{Text("FOCUS PROTECTION",color=Muted,fontSize=11.sp);Status("Shield",true);Status("Do Not Disturb",a.dndGranted());Status("Notifications silenced",a.dndGranted())};Primary("Begin focus"){if(goal.isNotBlank()){a.startFocus(goal,min);refresh()}}}}
@Composable fun Status(name:String,ok:Boolean){Row(Modifier.fillMaxWidth().padding(vertical=5.dp)){Icon(if(ok)Icons.Outlined.CheckCircle else Icons.Outlined.Warning,null,tint=if(ok)Mint else Warn);Spacer(Modifier.width(10.dp));Text(name);Spacer(Modifier.weight(1f));Text(if(ok)"Ready" else "Needs access",color=if(ok)Mint else Warn,fontSize=12.sp)}}
@Composable fun ActiveFocus(a:MainActivity,s:Store,refresh:()->Unit){var now by remember{mutableLongStateOf(System.currentTimeMillis())};var pending by remember{mutableStateOf<Session?>(null)};LaunchedEffect(Unit){while(true){now=System.currentTimeMillis();if(now>=s.p.getLong("focus_end",0)){pending=a.finish(false);break};delay(1000)}};pending?.let{Complete(a,it,refresh);return};val rem=(s.p.getLong("focus_end",0)-now).coerceAtLeast(0);Box(Modifier.fillMaxSize().background(Bg).padding(24.dp)){Column(Modifier.align(Alignment.Center),horizontalAlignment=Alignment.CenterHorizontally){Text("FOCUS",color=Mint,fontSize=12.sp,fontWeight=FontWeight.Bold);Text(String.format("%02d:%02d",rem/60000,(rem/1000)%60),fontSize=64.sp,fontWeight=FontWeight.Medium);Text(s.p.getString("goal","")?:"",fontSize=20.sp,fontWeight=FontWeight.SemiBold);Spacer(Modifier.height(36.dp));OutlinedButton(onClick={s.p.edit().putInt("focus_urges",s.p.getInt("focus_urges",0)+1).apply()}){Text("I feel an urge")};TextButton(onClick={IdeaSheet.show=true}){Text("+ Park idea")};IdeaSheet(a)};TextButton(onClick={pending=a.finish(true)},modifier=Modifier.align(Alignment.BottomCenter)){Text("End session",color=Muted)}}}
@Composable fun Complete(a:MainActivity,sess:Session,done:()->Unit){var output by remember{mutableStateOf("")};var score by remember{mutableIntStateOf(8)};Page("Complete"){Text("${sess.actual} minutes protected.",fontSize=34.sp,fontWeight=FontWeight.Bold);Text(sess.goal,color=Muted);Spacer(Modifier.height(20.dp));Text("What exists now?",fontWeight=FontWeight.SemiBold);OutlinedTextField(output,{output=it},Modifier.fillMaxWidth(),placeholder={Text("What did you produce?")});Text("FOCUS QUALITY",color=Muted,fontSize=11.sp,modifier=Modifier.padding(top=20.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){(1..10).forEach{x->FilterChip(selected=score==x,onClick={score=x},label={Text("$x")})}};CardX{Text("${sess.urges} urges · ${sess.actual}m deep work",color=Muted)};Primary("Save session"){a.complete(sess,score,output);done()}}}
@Composable fun Progress(a:MainActivity,s:Store,tick:Int){Page("Progress"){Text("Your attention is changing.",fontSize=31.sp,fontWeight=FontWeight.Bold);Text("7 DAYS",color=Mint,fontSize=12.sp);CardX{Text("DEEP WORK",color=Muted,fontSize=11.sp);Text("${s.total("mins")} min",fontSize=42.sp,fontWeight=FontWeight.Bold);Row(Modifier.fillMaxWidth().height(80.dp),verticalAlignment=Alignment.Bottom){val max=(1..7).maxOf{s.metric("mins",it)}.coerceAtLeast(1);(1..7).forEach{d->Column(Modifier.weight(1f),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Bottom){Box(Modifier.width(18.dp).height((60f*s.metric("mins",d)/max).dp.coerceAtLeast(3.dp)).background(if(d==s.day())Mint else Muted,RoundedCornerShape(6.dp)));Text("$d",color=Muted,fontSize=10.sp)}}}};Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){val n=s.total("sessions");Metric("FOCUS",if(n==0)"—" else "%.1f".format(s.total("focusSum").toDouble()/n),Modifier.weight(1f));Metric("URGES/H",if(s.total("mins")==0)"—" else "%.1f".format(s.total("urges")/(s.total("mins")/60.0)),Modifier.weight(1f))};if(s.day()==7){CardX{Text("7 DAYS LATER",color=Mint,fontWeight=FontWeight.Bold);Text("Before → Now",fontSize=26.sp,fontWeight=FontWeight.Bold);Text("Deep work  ${s.metric("mins",1)}m  →  ${s.metric("mins",7)}m",color=Muted);val b=s.metric("sessions",1);val n=s.metric("sessions",7);if(b>0&&n>0)Text("Focus  %.1f  →  %.1f".format(s.metric("focusSum",1).toDouble()/b,s.metric("focusSum",7).toDouble()/n),color=Muted)}}}}
@Composable fun More(a:MainActivity,s:Store,refresh:()->Unit){Page("More"){Text("Design your environment.",fontSize=31.sp,fontWeight=FontWeight.Bold);CardX{Text("PROTECTION",color=Muted,fontSize=11.sp);Setting("Focus Shield",s.p.getBoolean("shield_enabled",true)){s.p.edit().putBoolean("shield_enabled",it).apply()};Setting("Morning protection",s.p.getBoolean("morning_shield",true)){s.p.edit().putBoolean("morning_shield",it).apply()};Text("06:00 – 09:00",color=Muted)};CardX{Text("ANDROID ACCESS",color=Muted,fontSize=11.sp);Access("Do Not Disturb",a.dndGranted()){a.startActivity(Intent(Settings.ACTION_NOTIFICATION_POLICY_ACCESS_SETTINGS))};Access("Usage access",a.usage()!=null){a.startActivity(Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS))};Access("iOff Shield",false){a.startActivity(Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))};Access("Notification access",false){a.startActivity(Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS))}};CardX{Text("EXPERIMENT",color=Muted,fontSize=11.sp);(1..7).forEach{d->TextButton(onClick={s.p.edit().putInt("day",d).apply();refresh()}){Text("Day $d — ${Days[d-1]}",color=if(d==s.day())Mint else Ink)}}};Text("Your attention data stays on this device.",color=Muted,fontSize=13.sp)}}
@Composable fun Setting(name:String,value:Boolean,on:(Boolean)->Unit){Row(verticalAlignment=Alignment.CenterVertically){Text(name,Modifier.weight(1f));Switch(value,on)}}
@Composable fun Access(name:String,ok:Boolean,on:()->Unit){TextButton(onClick=on,Modifier.fillMaxWidth()){Icon(if(ok)Icons.Outlined.CheckCircle else Icons.Outlined.RadioButtonUnchecked,null,tint=if(ok)Mint else Warn);Spacer(Modifier.width(10.dp));Text(name,Modifier.weight(1f),color=Ink);Text(if(ok)"Ready" else "Enable",color=if(ok)Mint else Warn)}}
object IdeaSheet{var show by mutableStateOf(false)}
@Composable fun IdeaSheet(a:MainActivity){if(IdeaSheet.show){var text by remember{mutableStateOf("")};ModalBottomSheet(onDismissRequest={IdeaSheet.show=false},containerColor=Surface){Column(Modifier.padding(24.dp)){Text("Get it out of your head.",fontSize=25.sp,fontWeight=FontWeight.Bold);Text("Park it. Don't chase it.",color=Muted);OutlinedTextField(text,{text=it},Modifier.fillMaxWidth().padding(vertical=16.dp),placeholder={Text("Type an idea…")});OutlinedButton(onClick={a.voice();IdeaSheet.show=false},Modifier.fillMaxWidth()){Icon(Icons.Outlined.Mic,null);Text("  Voice")};Primary("Park & return"){a.park(text);IdeaSheet.show=false};Spacer(Modifier.height(24.dp))}}}}
