package cz.ioff.app

import android.app.*
import android.content.*
import android.os.*
import android.provider.Settings
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.*
import kotlinx.coroutines.delay
import org.json.*
import java.text.SimpleDateFormat
import java.util.*

val Bg=Color(0xFF080A0D);val Surface=Color(0xFF111419);val Elevated=Color(0xFF181C22);val Border=Color(0xFF252A32);val Ink=Color(0xFFF5F7F8);val Muted=Color(0xFF969DA8);val Mint=Color(0xFF8AFFB5);val Warn=Color(0xFFFFCC66);val Err=Color(0xFFFF7070)
data class Session(val start:Long,val end:Long,val experimentDay:Int,val planned:Int,val actual:Int,val urges:Int,val focus:Int,val goal:String,val output:String,val interrupted:Boolean)
class Store(c:Context){val p=c.getSharedPreferences("ioff",0);fun day()=p.getInt("day",1).coerceIn(1,7);fun k(x:String,d:Int=day())=MetricKeys.experiment(d,x);fun metric(x:String,d:Int=day())=p.getInt(k(x,d),0);fun add(x:String,n:Int,d:Int=day())=p.edit().putInt(k(x,d),metric(x,d)+n).apply();fun total(x:String)=(1..7).sumOf{metric(x,it)};fun sessions():List<Session>{val raw=p.getString("sessions_json","[]")?:"[]";return try{val a=JSONArray(raw);val r=mutableListOf<Session>();for(i in 0 until a.length()){val o=a.getJSONObject(i);r.add(Session(o.optLong("start"),o.optLong("end"),o.optInt("experimentDay",1),o.optInt("planned"),o.optInt("actual"),o.optInt("urges"),o.optInt("focus"),o.optString("goal"),o.optString("output"),o.optBoolean("interrupted")))};r}catch(_:Exception){emptyList()}};fun save(s:Session){val a=try{JSONArray(p.getString("sessions_json","[]")?:"[]")}catch(_:Exception){JSONArray()};a.put(JSONObject().put("start",s.start).put("end",s.end).put("experimentDay",s.experimentDay).put("planned",s.planned).put("actual",s.actual).put("urges",s.urges).put("focus",s.focus).put("goal",s.goal).put("output",s.output).put("interrupted",s.interrupted));p.edit().putString("sessions_json",a.toString()).apply();add("mins",s.actual,s.experimentDay);add("urges",s.urges,s.experimentDay);add("sessions",1,s.experimentDay);add("focusSum",s.focus,s.experimentDay)};fun ideas()=IdeaCodec.parse(p.getString("ideas","")?:"");fun park(t:String){p.edit().putString("ideas",IdeaCodec.prepend(p.getString("ideas","")?:"",System.currentTimeMillis(),t)).apply()};fun updateIdea(x:ParkedIdea,t:String){p.edit().putString("ideas",IdeaCodec.update(p.getString("ideas","")?:"",x.timestamp,t)).apply()};fun deleteIdea(x:ParkedIdea){p.edit().putString("ideas",IdeaCodec.delete(p.getString("ideas","")?:"",x.timestamp)).apply()}}
class MainActivity:ComponentActivity(){lateinit var store:Store;override fun onCreate(b:Bundle?){super.onCreate(b);store=Store(this);recover();setContent{Theme{Root(this,store)}}};fun startFocus(goal:String,min:Int){val g=FocusRules.normalizedGoal(goal);if(!FocusRules.canStart(g))return;val m=FocusRules.durationMinutes(min);val now=System.currentTimeMillis();val nm=getSystemService(NotificationManager::class.java);val e=store.p.edit().putBoolean("focus_active",true).putLong("focus_start",now).putLong("focus_end",now+m*60000L).putInt("focus_day",store.day()).putInt("focus_planned",m).putInt("focus_urges",0).putString("goal",g);if(nm?.isNotificationPolicyAccessGranted==true){e.putInt("prev_filter",nm.currentInterruptionFilter).putBoolean("dnd_changed",true);nm.setInterruptionFilter(NotificationManager.INTERRUPTION_FILTER_PRIORITY)};e.commit()};fun restoreDnd(){val nm=getSystemService(NotificationManager::class.java);if(store.p.getBoolean("dnd_changed",false)&&nm?.isNotificationPolicyAccessGranted==true){runCatching{nm.setInterruptionFilter(store.p.getInt("prev_filter",NotificationManager.INTERRUPTION_FILTER_ALL))};store.p.edit().putBoolean("dnd_changed",false).apply()}};fun recover(){if(store.p.getBoolean("focus_active",false)&&store.p.getLong("focus_end",0)<=System.currentTimeMillis()){restoreDnd();store.p.edit().putBoolean("focus_expired",true).apply()}};fun finish(interrupted:Boolean):Session{val p=store.p;val start=p.getLong("focus_start",System.currentTimeMillis());val planned=p.getInt("focus_planned",60);val actual=((System.currentTimeMillis()-start)/60000).toInt().coerceIn(0,planned);restoreDnd();return Session(start,System.currentTimeMillis(),p.getInt("focus_day",store.day()),planned,if(!interrupted&&actual<planned)planned else actual,p.getInt("focus_urges",0),0,p.getString("goal","")?:"","",interrupted)};fun complete(x:Session,score:Int,out:String){store.save(x.copy(focus=score,output=out.trim()));store.p.edit().putBoolean("focus_active",false).putBoolean("focus_expired",false).apply()};fun dnd()=getSystemService(NotificationManager::class.java)?.isNotificationPolicyAccessGranted==true}
@Composable fun Theme(c: @Composable () -> Unit){val base=Typography();MaterialTheme(colorScheme=darkColorScheme(primary=Mint,background=Bg,surface=Surface,surfaceVariant=Elevated,onBackground=Ink,onSurface=Ink,error=Err),typography=Typography(headlineLarge=base.headlineLarge.copy(fontWeight=FontWeight.Bold),titleLarge=base.titleLarge.copy(fontWeight=FontWeight.Bold)),content=c)}
@Composable fun Root(a:MainActivity,s:Store){var tab by remember{mutableIntStateOf(0)};var rev by remember{mutableIntStateOf(0)};var ideas by remember{mutableStateOf(false)};var shutdown by remember{mutableStateOf(false)};rev;val active=s.p.getBoolean("focus_active",false);if(ideas){Ideas(s){ideas=false;rev++};return};if(shutdown){Shutdown(s){shutdown=false;rev++};return};Scaffold(containerColor=Bg,bottomBar={if(!active)NavigationBar(containerColor=Surface,tonalElevation=0.dp){val names=listOf("Today","Focus","Progress","More");val icons=listOf(Icons.Outlined.Home,Icons.Outlined.Timer,Icons.Outlined.Insights,Icons.Outlined.Tune);names.indices.forEach{i->NavigationBarItem(selected=tab==i,onClick={tab=i},icon={Icon(icons[i],null)},label={Text(names[i])},colors=NavigationBarItemDefaults.colors(selectedIconColor=Bg,selectedTextColor=Mint,indicatorColor=Mint,unselectedIconColor=Muted,unselectedTextColor=Muted))}}}){pad->Box(Modifier.padding(pad)){if(active)Active(a,s){rev++}else when(tab){0->V05Today(s,{tab=1},{ideas=true});1->FocusSetup(a,s){rev++};2->AttentionProgress(s);else->More(a,s,{shutdown=true},{ideas=true})}}}}
@Composable fun Page(title:String,c: @Composable ColumnScope.() -> Unit){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(horizontal=20.dp,vertical=18.dp)){Row(verticalAlignment=Alignment.CenterVertically){Text("iOff",fontSize=27.sp,fontWeight=FontWeight.Black,color=Mint,letterSpacing=(-1).sp);Spacer(Modifier.weight(1f));Text(title.uppercase(),color=Muted,fontSize=10.sp,fontWeight=FontWeight.Bold,letterSpacing=1.2.sp)};Spacer(Modifier.height(24.dp));c();Spacer(Modifier.height(18.dp))}}
@Composable fun CardX(c: @Composable ColumnScope.() -> Unit){Card(modifier=Modifier.fillMaxWidth().padding(vertical=6.dp),shape=RoundedCornerShape(22.dp),colors=CardDefaults.cardColors(containerColor=Surface),border=BorderStroke(1.dp,Border)){Column(Modifier.padding(18.dp),content=c)}}
@Composable fun Primary(t:String,enabled:Boolean=true,on:()->Unit){Button(onClick=on,modifier=Modifier.fillMaxWidth().height(58.dp),enabled=enabled,shape=RoundedCornerShape(18.dp),colors=ButtonDefaults.buttonColors(containerColor=Mint,contentColor=Bg,disabledContainerColor=Border,disabledContentColor=Muted)){Text(t,fontWeight=FontWeight.Bold,fontSize=16.sp)}}
@Composable fun Metric(l:String,v:String,m:Modifier){Card(modifier=m.padding(vertical=5.dp),shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=Surface),border=BorderStroke(1.dp,Border)){Column(Modifier.padding(16.dp)){Text(l,color=Muted,fontSize=10.sp,fontWeight=FontWeight.Bold,letterSpacing=1.sp);Spacer(Modifier.height(5.dp));Text(v,fontSize=25.sp,fontWeight=FontWeight.Bold)}}}
@Composable fun SessionRow(x:Session){CardX{Row{Column(Modifier.weight(1f)){Text(x.goal,fontWeight=FontWeight.Bold,fontSize=17.sp);if(x.output.isNotBlank())Text(x.output,color=Muted,fontSize=12.sp,modifier=Modifier.padding(top=4.dp))};Text("${x.actual}m",color=Mint,fontWeight=FontWeight.Bold)};Text("${x.urges} urges  ·  ${if(x.focus>0)"focus ${x.focus}/10" else "not rated"}",color=Muted,fontSize=12.sp,modifier=Modifier.padding(top=9.dp))}}
@Composable fun FocusSetup(a:MainActivity,s:Store,done:()->Unit){var goal by remember{mutableStateOf(s.p.getString("focus_prefill","")?:"")};var min by remember{mutableIntStateOf(60)};Page("Focus"){Text("Finish one thing.",fontSize=35.sp,fontWeight=FontWeight.Bold,letterSpacing=(-1).sp);Text("Everything else can wait.",color=Muted,fontSize=15.sp,modifier=Modifier.padding(top=5.dp,bottom=18.dp));CardX{Text("WHAT ARE YOU FINISHING?",color=Muted,fontSize=10.sp,fontWeight=FontWeight.Bold);OutlinedTextField(goal,{goal=it},Modifier.fillMaxWidth().padding(top=8.dp),placeholder={Text("A concrete outcome")},shape=RoundedCornerShape(18.dp));Text("DURATION",color=Muted,fontSize=10.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=18.dp,bottom=6.dp));Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(7.dp)){listOf(30,60,90,120).forEach{FilterChip(min==it,{min=it},{Text("${it} min")})}}};CardX{Row(verticalAlignment=Alignment.CenterVertically){Surface(color=if(a.dnd())Mint.copy(alpha=.12f) else Warn.copy(alpha=.12f),shape=RoundedCornerShape(14.dp)){Icon(Icons.Outlined.Shield,null,tint=if(a.dnd())Mint else Warn,modifier=Modifier.padding(10.dp))};Column(Modifier.padding(start=12.dp)){Text("Focus Protection",fontWeight=FontWeight.Bold);Text(if(a.dnd())"Do Not Disturb is ready" else "Enable Do Not Disturb access",color=if(a.dnd())Mint else Warn,fontSize=12.sp)}}};Primary("Begin Focus  →",goal.isNotBlank()){a.startFocus(goal,min);done()}}}
@Composable fun Active(a:MainActivity,s:Store,done:()->Unit){var now by remember{mutableLongStateOf(System.currentTimeMillis())};var pending by remember{mutableStateOf<Session?>(null)};var park by remember{mutableStateOf(false)};LaunchedEffect(Unit){while(pending==null){now=System.currentTimeMillis();if(now>=s.p.getLong("focus_end",0)){pending=a.finish(false);break};delay(1000)}};pending?.let{Complete(a,it,done);return};val rem=(s.p.getLong("focus_end",0)-now).coerceAtLeast(0);Box(Modifier.fillMaxSize().background(Bg).padding(24.dp)){Column(Modifier.align(Alignment.Center),horizontalAlignment=Alignment.CenterHorizontally){Surface(color=Mint.copy(alpha=.10f),shape=RoundedCornerShape(50.dp)){Text("●  FOCUS ACTIVE",color=Mint,fontSize=11.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(horizontal=15.dp,vertical=8.dp))};Spacer(Modifier.height(24.dp));Text(String.format("%02d:%02d",rem/60000,(rem/1000)%60),fontSize=68.sp,fontWeight=FontWeight.Black,letterSpacing=(-3).sp);Text(s.p.getString("goal","")?:"",fontSize=19.sp,fontWeight=FontWeight.SemiBold,modifier=Modifier.padding(top=8.dp),color=Ink);Text("One task. One screen.",color=Muted,fontSize=13.sp,modifier=Modifier.padding(top=5.dp,bottom=28.dp));Row(horizontalArrangement=Arrangement.spacedBy(10.dp)){OutlinedButton({s.p.edit().putInt("focus_urges",s.p.getInt("focus_urges",0)+1).apply()},shape=RoundedCornerShape(16.dp)){Text("⚡ Urge")};OutlinedButton({park=true},shape=RoundedCornerShape(16.dp)){Text("＋ Park idea")}}};TextButton({pending=a.finish(true)},Modifier.align(Alignment.BottomCenter)){Text("End session",color=Muted)}};if(park){var t by remember{mutableStateOf("")};AlertDialog(onDismissRequest={park=false},confirmButton={Button(onClick={s.park(t);park=false},enabled=t.isNotBlank()){Text("Park")}},dismissButton={TextButton({park=false}){Text("Cancel")}},title={Text("Park the idea")},text={OutlinedTextField(t,{t=it},placeholder={Text("Capture it. Don't switch projects.")},shape=RoundedCornerShape(16.dp))})}}
@Composable fun Complete(a:MainActivity,x:Session,done:()->Unit){var out by remember{mutableStateOf("")};var score by remember{mutableIntStateOf(8)};Page("Complete"){Text("Protected.",color=Mint,fontSize=12.sp,fontWeight=FontWeight.Bold);Text("${x.actual} minutes of real work.",fontSize=34.sp,fontWeight=FontWeight.Bold,letterSpacing=(-1).sp,modifier=Modifier.padding(bottom=18.dp));CardX{OutlinedTextField(out,{out=it},Modifier.fillMaxWidth(),label={Text("What exists now?")},shape=RoundedCornerShape(18.dp));Text("FOCUS QUALITY",color=Muted,fontSize=10.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=18.dp));Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(5.dp)){(1..10).forEach{FilterChip(score==it,{score=it},{Text("$it")})}}};Primary("Save session  ✓"){a.complete(x,score,out);done()}}}
@Composable fun Ideas(s:Store,back:()->Unit){var q by remember{mutableStateOf("")};var edit by remember{mutableStateOf<ParkedIdea?>(null)};var rev by remember{mutableIntStateOf(0)};var add by remember{mutableStateOf("")};rev;Page("Ideas"){Row(verticalAlignment=Alignment.CenterVertically){TextButton(back){Text("← Back",color=Muted)};Spacer(Modifier.weight(1f));Button({if(add.isNotBlank()){s.park(add);add="";rev++}},enabled=add.isNotBlank(),shape=RoundedCornerShape(16.dp)){Text("+ Park idea")}};Text("Idea Parking",fontSize=35.sp,fontWeight=FontWeight.Bold,letterSpacing=(-1).sp);Text("Capture it. Don't switch projects.",color=Muted,modifier=Modifier.padding(top=4.dp,bottom=16.dp));OutlinedTextField(add,{add=it},Modifier.fillMaxWidth(),placeholder={Text("What's pulling at your attention?")},shape=RoundedCornerShape(18.dp));OutlinedTextField(q,{q=it},Modifier.fillMaxWidth().padding(top=9.dp),leadingIcon={Icon(Icons.Outlined.Search,null)},placeholder={Text("Search parked ideas")},shape=RoundedCornerShape(18.dp));val shown=s.ideas().filter{q.isBlank()||it.text.contains(q,true)};Text("${shown.size} IDEAS",color=Muted,fontSize=10.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=18.dp));shown.forEach{x->CardX{Row{Column(Modifier.weight(1f)){Text(x.text,fontSize=17.sp,fontWeight=FontWeight.SemiBold);Text(SimpleDateFormat("EEE, MMM d · HH:mm",Locale.getDefault()).format(Date(x.timestamp)),color=Muted,fontSize=11.sp,modifier=Modifier.padding(top=5.dp))};IconButton({edit=x}){Icon(Icons.Outlined.Edit,null,tint=Muted)};IconButton({s.deleteIdea(x);rev++}){Icon(Icons.Outlined.DeleteOutline,null,tint=Muted)}};Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){IdeaState.entries.forEach{state->FilterChip(selected=x.state==state,onClick={s.p.edit().putString("ideas",IdeaCodec.setState(s.p.getString("ideas","")?:"",x.timestamp,state)).apply();rev++},label={Text(state.name)})}}}}};edit?.let{x->var t by remember(x){mutableStateOf(x.text)};AlertDialog({edit=null},{Button({s.updateIdea(x,t);edit=null;rev++}){Text("Save")}},dismissButton={TextButton({edit=null}){Text("Cancel")}},text={OutlinedTextField(t,{t=it},shape=RoundedCornerShape(16.dp))},title={Text("Edit idea")})}}
@Composable fun More(a:MainActivity,s:Store,shutdown:()->Unit,ideas:()->Unit){var reset by remember{mutableStateOf(false)};Page("More"){Text("Design your environment.",fontSize=34.sp,fontWeight=FontWeight.Bold,letterSpacing=(-1).sp);Text("Make focus the default, not a daily negotiation.",color=Muted,modifier=Modifier.padding(top=5.dp,bottom=15.dp));CardX{MenuRow(Icons.Outlined.Lightbulb,"Idea Parking","${s.ideas().size} parked",ideas);HorizontalDivider(color=Border);MenuRow(Icons.Outlined.NightsStay,"Daily Shutdown",if(s.p.getBoolean("shutdown_done_${s.day()}",false))"Done today" else "1 minute",shutdown)};SectionLabel("Protection");CardX{MenuRow(Icons.Outlined.DoNotDisturb,"Do Not Disturb",if(a.dnd())"Ready" else "Needs access"){a.startActivity(Intent(Settings.ACTION_NOTIFICATION_POLICY_ACCESS_SETTINGS))};HorizontalDivider(color=Border);MenuRow(Icons.Outlined.Shield,"Focus Shield","Accessibility"){a.startActivity(Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))};HorizontalDivider(color=Border);MenuRow(Icons.Outlined.Insights,"Usage Access","Attention metrics"){a.startActivity(Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS))}};CardX{var on by remember{mutableStateOf(s.p.getBoolean("morning_shield",true))};Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("Morning Protection",fontWeight=FontWeight.Bold);Text("06:00–09:00 · protect the first hours",color=Muted,fontSize=12.sp)};Switch(on,{on=it;s.p.edit().putBoolean("morning_shield",it).apply()})}};SectionLabel("Testing");CardX{TextButton({reset=true}){Icon(Icons.Outlined.RestartAlt,null,tint=Err);Spacer(Modifier.width(8.dp));Text("Reset all data",color=Err)}}};if(reset)AlertDialog(onDismissRequest={reset=false},confirmButton={Button({s.p.edit().clear().apply();reset=false}){Text("Reset")}},dismissButton={TextButton({reset=false}){Text("Cancel")}},title={Text("Reset all data?")},text={Text("This removes focus history, ideas and daily tracking.")})}
@Composable fun MenuRow(icon:androidx.compose.ui.graphics.vector.ImageVector,title:String,sub:String,on:()->Unit){Row(Modifier.fillMaxWidth().clickable(onClick=on).padding(vertical=11.dp),verticalAlignment=Alignment.CenterVertically){Surface(color=Elevated,shape=RoundedCornerShape(13.dp)){Icon(icon,null,tint=Mint,modifier=Modifier.padding(9.dp))};Column(Modifier.padding(start=12.dp).weight(1f)){Text(title,fontWeight=FontWeight.SemiBold);Text(sub,color=Muted,fontSize=12.sp)};Icon(Icons.Outlined.ChevronRight,null,tint=Muted)}}