package cz.ioff.app

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@Composable fun SectionLabel(t:String){Text(t.uppercase(),color=Muted,fontSize=11.sp,fontWeight=FontWeight.SemiBold,letterSpacing=1.3.sp,modifier=Modifier.padding(top=18.dp,bottom=8.dp))}
@Composable fun V05Today(s:Store,onFocus:()->Unit,onIdeas:()->Unit){
 val d=s.day();val ctx=LocalContext.current;var usageRev by remember{mutableIntStateOf(0)};LaunchedEffect(d){UsageMetrics.collect(ctx,s.p,d);usageRev++};usageRev
 var one by remember(d){mutableStateOf(s.p.getString("one_thing_$d","")?:"")};val ls=remember{DailyLifeStore.from(s.p)};var life by remember(d){mutableStateOf(ls.load(d))};val n=s.metric("sessions",d);val snap=AttentionSnapshot(s.metric("mins",d),if(n==0)0.0 else s.metric("focusSum",d).toDouble()/n,s.metric("urges",d),s.metric("shield",d),s.metric("bypasses",d),s.metric("distracting",d));val score=AttentionEngine.score(snap)
 Page("Day $d of 7"){
  Text("Protect what matters.",fontSize=34.sp,fontWeight=FontWeight.Bold,letterSpacing=(-1).sp);Text("One result. Less noise. Finish the day with proof.",color=Muted,fontSize=15.sp,modifier=Modifier.padding(top=6.dp,bottom=18.dp))
  CardX{SectionLabel("Today's one thing");OutlinedTextField(one,{one=it;s.p.edit().putString("one_thing_$d",it).apply()},Modifier.fillMaxWidth(),placeholder={Text("The one result that makes today count")},shape=RoundedCornerShape(18.dp));Spacer(Modifier.height(12.dp));Primary("Start Focus  →",enabled=one.isNotBlank()){s.p.edit().putString("focus_prefill",one.trim()).apply();onFocus()}}
  Row(horizontalArrangement=Arrangement.spacedBy(10.dp)){Metric("ATTENTION","$score",Modifier.weight(1f));Metric("DEEP WORK","${s.metric("mins",d)}m",Modifier.weight(1f))};Row(horizontalArrangement=Arrangement.spacedBy(10.dp)){Metric("APP OPENS","${s.metric("opens",d)}",Modifier.weight(1f));Metric("DISTRACTING","${s.metric("distracting",d)}m",Modifier.weight(1f))};Row(horizontalArrangement=Arrangement.spacedBy(10.dp)){Metric("URGES","${s.metric("urges",d)}",Modifier.weight(1f));Metric("SHIELDS","${s.metric("shield",d)}",Modifier.weight(1f))}
  SectionLabel("Daily commitments");CardX{DailyCheck("No drugs","Clear mind",life.noDrugs){life=life.copy(noDrugs=it);ls.save(d,life)};HorizontalDivider(color=Border);DailyCheck("No weed","Stay sharp",life.noWeed){life=life.copy(noWeed=it);ls.save(d,life)};HorizontalDivider(color=Border);DailyCheck("No alcohol","Protect tomorrow",life.noAlcohol){life=life.copy(noAlcohol=it);ls.save(d,life)}}
  SexBox(d,life,ls){life=ls.load(d)};SportBox(d,life,ls){life=ls.load(d)}
  CardX{Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("Idea Parking",fontSize=19.sp,fontWeight=FontWeight.Bold);Text("Capture it. Don't switch projects.",color=Muted,fontSize=13.sp)};FilledTonalButton(onClick=onIdeas,shape=RoundedCornerShape(16.dp)){Text("${s.ideas().size}  View")}}};val sessions=s.sessions().filter{it.experimentDay==d};if(sessions.isNotEmpty()){SectionLabel("Today's focus");sessions.takeLast(3).reversed().forEach{SessionRow(it)}}
 }
}
@Composable private fun DailyCheck(label:String,sub:String,value:Boolean,set:(Boolean)->Unit){Row(Modifier.fillMaxWidth().heightIn(min=58.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(label,fontWeight=FontWeight.SemiBold);Text(sub,color=Muted,fontSize=12.sp)};Checkbox(value,set)}}
@Composable private fun SexBox(day:Int,life:DailyLife,store:DailyLifeStore,refresh:()->Unit){var note by remember{mutableStateOf("")};CardX{Text("Sex",fontSize=19.sp,fontWeight=FontWeight.Bold);Text("Log events, not just a checkbox. ${life.sexEvents.size} today.",color=Muted,fontSize=12.sp);life.sexEvents.forEach{x->Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text(if(x.note.isBlank())"Sex" else x.note,Modifier.weight(1f));TextButton({store.deleteSex(day,x.id);refresh()}){Text("Remove",color=Muted)}}};OutlinedTextField(note,{note=it},Modifier.fillMaxWidth(),placeholder={Text("Optional note")},shape=RoundedCornerShape(16.dp));Spacer(Modifier.height(8.dp));FilledTonalButton({store.addSex(day,note);note="";refresh()},shape=RoundedCornerShape(16.dp)){Text("+ Log sex")}}}
@Composable private fun SportBox(day:Int,life:DailyLife,store:DailyLifeStore,refresh:()->Unit){var activity by remember{mutableStateOf("")};var mins by remember{mutableStateOf("")};CardX{Text("Sport",fontSize=19.sp,fontWeight=FontWeight.Bold);Text("Movement counts. Add every session.",color=Muted,fontSize=12.sp);life.sports.forEach{x->Surface(color=Elevated,shape=RoundedCornerShape(16.dp),modifier=Modifier.fillMaxWidth().padding(top=8.dp)){Row(Modifier.padding(12.dp),verticalAlignment=Alignment.CenterVertically){Text("${x.activity}${if(x.minutes>0)"  ·  ${x.minutes} min" else ""}",Modifier.weight(1f));TextButton({store.deleteSport(day,x.id);refresh()}){Text("Remove",color=Muted)}}}};Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(activity,{activity=it},Modifier.weight(1.4f),placeholder={Text("Activity")},shape=RoundedCornerShape(16.dp));OutlinedTextField(mins,{mins=it.filter(Char::isDigit)},Modifier.weight(.7f),placeholder={Text("Min")},shape=RoundedCornerShape(16.dp))};Spacer(Modifier.height(8.dp));FilledTonalButton({store.addSport(day,activity,mins.toIntOrNull()?:0);activity="";mins="";refresh()},enabled=activity.isNotBlank(),shape=RoundedCornerShape(16.dp)){Text("+ Add activity")}}}
@Composable fun Shutdown(s:Store,onSaved:()->Unit){val d=s.day();var finished by remember{mutableStateOf(s.p.getString("shutdown_finished_$d","")?:"")};var stole by remember{mutableStateOf(s.p.getString("shutdown_stole_$d","")?:"")};var tomorrow by remember{mutableStateOf(s.p.getString("shutdown_tomorrow_$d","")?:"")};Page("Shutdown"){Text("Close the loops.",fontSize=34.sp,fontWeight=FontWeight.Bold);Text("60 seconds. Learn from today, then leave it.",color=Muted,modifier=Modifier.padding(bottom=18.dp));CardX{OutlinedTextField(finished,{finished=it},Modifier.fillMaxWidth(),label={Text("What did I finish today?")});OutlinedTextField(stole,{stole=it},Modifier.fillMaxWidth(),label={Text("What stole my attention?")});OutlinedTextField(tomorrow,{tomorrow=it},Modifier.fillMaxWidth(),label={Text("Tomorrow's One Thing")})};Primary("Save & Close Day  ✓"){s.p.edit().putString("shutdown_finished_$d",finished).putString("shutdown_stole_$d",stole).putString("shutdown_tomorrow_$d",tomorrow).putBoolean("shutdown_done_$d",true).putString("one_thing_${(d+1).coerceAtMost(7)}",tomorrow).apply();onSaved()}}}
@Composable fun AttentionProgress(s:Store){val sessions=s.sessions();val n=s.total("sessions");val avg=if(n==0)0.0 else s.total("focusSum").toDouble()/n;val snap=AttentionSnapshot(s.total("mins"),avg,s.total("urges"),s.total("shield"),s.total("bypasses"),s.total("distracting"));val score=AttentionEngine.score(snap);Page("Progress"){Text("Your attention, visible.",fontSize=34.sp,fontWeight=FontWeight.Bold);Text("Transparent metrics. No mystery score.",color=Muted,modifier=Modifier.padding(bottom=14.dp));CardX{Text("ATTENTION SCORE",color=Muted,fontSize=11.sp);Text("$score / 100",fontSize=54.sp,fontWeight=FontWeight.Bold,color=Mint);LinearProgressIndicator(progress={score/100f},modifier=Modifier.fillMaxWidth().height(8.dp),color=Mint,trackColor=Border)};Row(horizontalArrangement=Arrangement.spacedBy(10.dp)){Metric("DEEP WORK","${s.total("mins")}m",Modifier.weight(1f));Metric("APP OPENS","${s.total("opens")}",Modifier.weight(1f))};Row(horizontalArrangement=Arrangement.spacedBy(10.dp)){Metric("DISTRACTING","${s.total("distracting")}m",Modifier.weight(1f));Metric("BYPASSES","${s.total("bypasses")}",Modifier.weight(1f))};AttentionEngine.insight(sessions)?.let{CardX{Text("PERSONAL INSIGHT",color=Mint,fontSize=11.sp,fontWeight=FontWeight.Bold);Text(it,fontSize=17.sp)}};SectionLabel("7-day experiment");(1..7).forEach{d->CardX{Text("Day $d",fontWeight=FontWeight.SemiBold);Text("${s.metric("mins",d)} min deep work · ${s.metric("opens",d)} opens · ${s.metric("distracting",d)} min distracting",color=Muted,fontSize=12.sp)}}}}
